name: 'ThirdReality Motion Sensor'
packageKey: 'thirdreality-motion-sensor'
permissions:
  zigbee: {}
description: "Drivers for ThirdReality Smart Motion Sensor R1 and Smart Presence Sensor R2"
vendorSupportInformation: "https://www.3reality.com/"
